baseURL = "https://blabla/"
languageCode = "en-us"
title = "blabla"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
theme = "simple"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "blabla"
  [languages.fr]
    languageName = "Français"
    weight = 2
    title = "blabla"
  [languages.ar]
    languageName = "العربية"
    weight = 3
    title = "blabla"