
baseURL = "https://blabla.pages.dev/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "BlaBla Site"
theme = "blabla-theme"

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
  [languages.ar]
    languageName = "العربية"
    weight = 3
    languageDirection = "rtl"

