
baseURL = 'https://high-tech.pages.dev/'
languageCode = 'fr-FR'
title = 'High-Tech — Nouvelles Technologies, Tests et Comparatifs'
theme = 'high-tech-theme'
DefaultContentLanguage = 'fr'
[pagination]
  pagerSize = 10

[params]
  mainColor = 'emerald-400'
  favicon = 'favicon.png'

[pagination]
  pagerSize = 10

[languages]
  [languages.fr]
    languageName = 'Français'
    weight = 1
  [languages.en]
    languageName = 'English'
    weight = 2
  [languages.ar]
    languageName = 'العربية'
    weight = 3
